// <auto-generated />
using CarRental.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarRental.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190814145838_AddCarToDb")]
    partial class AddCarToDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CarRental.Model.Car", b =>
                {
                    b.Property<string>("registrationNumber")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("available");

                    b.Property<string>("carBrand")
                        .IsRequired();

                    b.Property<string>("carColor")
                        .IsRequired();

                    b.Property<float>("carDeposit");

                    b.Property<string>("carDescription")
                        .IsRequired();

                    b.Property<string>("carModel")
                        .IsRequired();

                    b.Property<float>("carPrice");

                    b.Property<string>("engineCapacity")
                        .IsRequired();

                    b.Property<string>("fuelType")
                        .IsRequired();

                    b.Property<string>("gearboxType")
                        .IsRequired();

                    b.Property<string>("numberOfDoors")
                        .IsRequired();

                    b.Property<string>("yearOfProduction")
                        .IsRequired();

                    b.HasKey("registrationNumber");

                    b.ToTable("Car");
                });
#pragma warning restore 612, 618
        }
    }
}
